name: Build Lem Variants

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.backend }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15
          # - macos-15-intel # sbcl is not supported for macos-15-intel
        backend:
          - lem-ncurses
          - lem-sdl2
          - lem-webview

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check flake
        run: nix flake check --all-systems --no-build

      - name: Build ${{ matrix.backend }}
        run: nix build .#${{ matrix.backend }} --print-build-logs
